========================================================================================================================
===============================================         LOG FILE         ===============================================
========================================================================================================================
2024-07-14 09:52:29,438 - INFO - Processing category: world-records
2024-07-14 09:52:37,144 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18b6f92d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f95b12aa92853e1d6d9011753de1728e
2024-07-14 09:52:37,144 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18b6f8810>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f95b12aa92853e1d6d9011753de1728e
2024-07-14 09:52:37,144 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff18b6fa4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/f95b12aa92853e1d6d9011753de1728e
